[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_escrow_demo = "6Ydap2iuD2VXnZEDnWLmuPERSRMDC8aLUrwDhxUMAuBR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mitrofan.tw/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
